//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class BillInfo
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public Nullable<int> ServiceRefNo { get; set; }
        [DataMember]
        public Nullable<int> ItemId { get; set; }
        [DataMember]
        public Nullable<decimal> Price { get; set; }
        [DataMember]
        public Nullable<decimal> Qty { get; set; }
        [DataMember]
        public Nullable<decimal> ItemAmount { get; set; }
    
        public virtual ItemsInfo ItemsInfo { get; set; }
        public virtual ServiceRecordInfo ServiceRecordInfo { get; set; }
    }
}
